User permissions implemented
hammadtariq/inventory-system-nextjs pull request #27
Opened 2021-12-28 16:10 UTC by rehanyahya

2021-12-28 16:59 UTC, DaniyalKukda requested changes

2021-12-28 16:59 UTC, DaniyalKukda commented on pages/login.js
> +        console.log(data.user);
please remove console.log

2021-12-28 16:59 UTC, DaniyalKukda commented on pages/login.js
> +        localStorage.setItem("user", JSON.stringify(data.user));
can we write a util function for local storage get and set to reduce redundancy and handle exceptions because sometime the window object is undefined

2021-12-28 16:59 UTC, DaniyalKukda commented on package.json
> +    "lodash": "^4.17.21",
I don't think we need lodash right now.

2021-12-30 07:09 UTC, hammadtariq commented on package.json
> +    "lodash": "^4.17.21",
that's okay, we will be using it.

2021-12-30 07:09 UTC, merged